// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Netflix.Servo")]
[assembly: AssemblyDescriptionAttribute("Netflix.Servo.NET")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Netflix.Servo")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2015")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0-beta.1+29.Branch.release/0.1.0.Sha.46fe110a04bdbd74f9ed85c262a8716c82859028")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.0";
    }
}
