// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Netflix.Servo")]
[assembly: AssemblyDescriptionAttribute("Netflix.Servo.NET")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Netflix.Servo")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2015")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0+28.Branch.master.Sha.3cf55da2a47d981fd1bfcbd20eb4f5fe6477189c")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.0";
    }
}
